# Generated by Django 2.2.9 on 2020-03-13 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='mainimage',
            field=models.ImageField(blank=True, upload_to='mainimage'),
        ),
    ]
