# Generated by Django 2.2.9 on 2020-03-13 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200313_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='mainimage',
            field=models.ImageField(blank=True, default='products/default.jpg', upload_to='products/'),
        ),
    ]
