# Generated by Django 2.2.9 on 2020-03-13 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200313_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='mainimage',
            field=models.ImageField(upload_to='mainimage'),
        ),
    ]
